apiVersion: v1
kind: Pod
metadata:
  name: wasm-http-server
  annotations:
    module.wasm.image/variant: compat
  labels:
    name: wasm-http-server
spec:
  containers:
  - name: http-server
    image: quay.io/ifont/wasm_http_server:latest
    command: [ "/http_server.wasm" ]
    ports:
    - containerPort: 1234
      protocol: TCP
    livenessProbe:
      tcpSocket:
        port: 1234
      initialDelaySeconds: 3
      periodSeconds: 30
    imagePullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - "ALL"
